<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<script src="estilos/js/jquery-3.5.1.js"></script>

<link rel="stylesheet" href="estilos/bootstrap-4.5.css">
<link rel="stylesheet" href="estilos/formatos.css">

<!-- <link rel="stylesheet" href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css"> -->
<link rel="stylesheet" href="estilos/dataTables.min.css">

<link rel="stylesheet" href="estilos/font-awesome-all.css">

<!-- <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script> -->
<!-- <link rel="stylesheet" href="estilos/SweetAlert/sweetalert2.min.css"> -->
<script src="estilos/SweetAlert/sweetalert2.min.js"></script> 

<script src="estilos/js/notify.min.js"></script>
<script src="estilos/js/functions.js"></script>

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
   	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
 <![endif]-->
 
 <!-- <meta http-equiv="refresh" content="180;url=codigos/salir.php"> -->