<div class="border">
	<div class="row p-2">
		<div class="col-md-10">
			<div class="input-group ml-3">
				<div class="input-group-prepend">
					<span class="input-group-text" id="">Buscar</span>
				</div>
				<input type="text" class="form-control" placeholder="" aria-label="" aria-describedby="">
			</div>
		</div>
		<div class="col-md-2">
			<a class="nav-link salir" href="codigos/salir.php">Cerrar Sesión</a>
		</div>
	</div>
</div>
